### ISSUE TITLE
Version 4+ generates virtual method rather than override

### ISSUE THREAD

**Issue by jeremy-morren** [Fody/Equals#330] opened 2021-03-30 19:24 UTC
I am compiling against .NET Standard 2.0.  After inspecting dll with JetBrains dotPeek, I noticed that v4+ is generating methods as virtual, rather than override.  v3 and before are generating override.  

v4.0 output:

    [GeneratedCode("Equals.Fody", "4.0.0.0")]
    [DebuggerNonUserCode]
    public virtual bool Equals(object obj) { ... }

    [GeneratedCode("Equals.Fody", "4.0.0.0")]
    [DebuggerNonUserCode]
    public virtual int GetHashCode() => ...

v3.1 output:

    [GeneratedCode("Equals.Fody", "3.1.0.0")]
    [DebuggerNonUserCode]
    public override bool Equals(object obj) { ... }

    [GeneratedCode("Equals.Fody", "3.1.0.0")]
    [DebuggerNonUserCode]
    public override int GetHashCode() => ...

**Comment by ltrzesniewski** [comment] 2021-04-03 11:07
Hi, I cannot reproduce this. The output of v3.1.0 and v4.0.1 only differs by the `GeneratedCode` attribute when used with Fody v6.5.0.

Can you test this with a different decompiler (such as ILSpy or dnSpy for instance)?

**Comment by tom-englert** [comment] 2021-09-11 14:01
Closed as no reproducible

**Closed by tom-englert** 2021-09-11 14:01 UTC
